### ISSUE TITLE
[Bug] Error in loading furniture

### ISSUE THREAD

**Issue by ClayLivince** [TexTools/xivModdingFramework#37]
while using xivModdigFramework to export some furniture to .obj I got lots of exceptions saying "Source array was not long enough. Check srcIndex and length, and the array's lower bounds". Problem seems originated from bad offset configuration. Some models can't be read normally, such as "Grade 3 Picture Frame" or “Tier 3 Aquarium”. And a lot of models have texture linking problems such as "Indoor Oriental Garden". Only those has only one texture or meshgroup things seems to be correct and normal.

Textools also impacted by this issue. These things I mentioned above could not be opened in textools either, and those have texture linking problems were displayed as black squares.

**Comment by Squall-Leonhart** [comment]
This has been resolved for the upcoming DT release, an EW compatible beta will be made available in the interim.

**Comment by Squall-Leonhart** [comment]
Little premature on close, the oriental garden is still showing black squares

**Comment by Squall-Leonhart** [comment]
The furnishings with black squares have parts that are referencing a diffuse only, with no existing specular or normal in the game data, so this is not a linking issue but a rendering issue.
