### ISSUE TITLE
[BUG] Error when directory is divided by `\`

### ISSUE THREAD

**Issue by Bluefissure** [TexTools/xivModdingFramework#41]
Should use `Path.GetDirectoryName` instead of substring in https://github.com/TexTools/xivModdingFramework/blob/1235f17/xivModdingFramework/SqPack/DataContainers/IndexFile.cs#L525

Doc: https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getdirectoryname?view=netframework-4.7

**Comment by KoraLyn** [comment]
Should be fixed with https://github.com/TexTools/xivModdingFramework/commit/ddeb2acf263b788551322bbd977d52856081a27d

**Comment by KoraLyn** [comment]
Out of curiosity, what made you run into an issue with this? All internal paths use `/` as separator afaik.

**Comment by Bluefissure** [comment]
> Out of curiosity, what made you run into an issue with this? All internal paths use `/` as separator afaik.

From other modding tools such as Penumbra and XivAlex
