### ISSUE TITLE
.tex handling when mipmap size is a multiple of 16000 causes loss of data

### ISSUE THREAD

**Issue by Soreepeong** [TexTools/xivModdingFramework#51]
In the following code, shouldn't

> `uncompLength = dealing with last part ? mipLength % 16000 : 16000`

have been

> `uncompLength = dealing with last part && mipLength % 16000 != 0 ? mipLength % 16000 : 16000`

instead? Otherwise, the last part of each mipmap would end up being omitted.

https://github.com/TexTools/xivModdingFramework/blob/12efd03145dd8f03f132699e8ef2cd757dc1fed6/xivModdingFramework/Textures/FileTypes/DDS.cs#L526-L554

[This mod](https://xivmodarchive.com/modid/38907) has consecutive sqblocks where (size=16b, unk=0, compressed=0 decompressed=16000), and while I'm not sure if the above is the cause (can't think of a reason why would these empty blocks be placed consecutive), thought that it might worth sharing this issue.

![image](https://cdn.discordapp.com/attachments/929533532185956352/1024243667021594634/unknown.png)

**Comment by Soreepeong** [comment]
On consecutive invalid empty blocks, it might be the case of the game storing .tex files truncated if it ends with bunch of trailing zeroes, resulting in truncated .tex file, which makes ReadBytes return zero length array, in which case maybe it can just stop there?

**Comment by Lunaretic** [comment]
Resolved in Dawntrail builds as part of other refactoring.
